(() => {
  const name = document.querySelector('title')?.textContent?.split('|')[0]?.trim() || 'this restaurant';
  const palette = {"Barrington's":['#1e2926','Georgia,serif'],"Duckworth's":['#132c43','Arial,sans-serif'],HopFly:['#19201d','Arial,sans-serif'],Idlewild:['#22201e','Georgia,serif'],'Lenny Boy':['#20352d','Arial,sans-serif']};
  const match = Object.entries(palette).find(([label]) => name.includes(label));
  if (match) { document.documentElement.style.setProperty('--c', match[1][0]); document.documentElement.style.setProperty('--font', match[1][1]); }
  const style = document.createElement('style');
  style.textContent = `html,body{max-width:100%;overflow-x:clip}.prospect-tool{position:fixed;right:18px;bottom:18px;z-index:99;border:0;border-radius:999px;padding:13px 17px;background:#141414;color:#fff;font:700 14px system-ui;box-shadow:0 8px 24px #0004;cursor:pointer}.prospect-tool:focus{outline:3px solid #f1b84b;outline-offset:3px}.prospect-dialog{max-width:620px;width:calc(100% - 32px);border:0;border-radius:16px;padding:0;color:#1c1c1c;box-shadow:0 24px 80px #0008}.prospect-dialog::backdrop{background:#000a}.prospect-panel{padding:24px}.prospect-close{float:right;border:0;background:transparent;font-size:24px;cursor:pointer}.prospect-options{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.prospect-options button,.prospect-panel button[type=submit]{border:1px solid #333;border-radius:8px;background:#fff;padding:10px 12px;font:600 14px system-ui;cursor:pointer}.prospect-options button[aria-pressed=true],.prospect-panel button[type=submit]{background:#151515;color:#fff}.prospect-panel label{display:block;margin:14px 0 6px;font:600 14px system-ui}.prospect-panel select{width:100%;padding:10px;border:1px solid #777;border-radius:7px;font:inherit}.prospect-result{min-height:24px;margin:14px 0;padding:10px 0;border-top:1px solid #ddd;border-bottom:1px solid #ddd}.prospect-note{font-size:12px;color:#555}`;
  document.head.append(style);
  const button = document.createElement('button'); button.className = 'prospect-tool'; button.type = 'button'; button.textContent = 'Plan your visit';
  const dialog = document.createElement('dialog'); dialog.className = 'prospect-dialog';
  dialog.innerHTML = `<div class="prospect-panel"><button class="prospect-close" type="button" aria-label="Close visit planner">×</button><p class="prospect-note">Unofficial concept tool · no details are sent</p><h2>Plan a visit to ${name}</h2><p>Choose what matters most and get a simple on-site recommendation.</p><div class="prospect-options" aria-label="Visit preference"><button type="button" aria-pressed="false" data-p="food">Food first</button><button type="button" aria-pressed="false" data-p="drinks">Drinks first</button><button type="button" aria-pressed="false" data-p="group">With a group</button><button type="button" aria-pressed="false" data-p="easy">Keep it easy</button></div><div class="prospect-result" aria-live="polite">Choose a preference to see a suggested next step.</div><form><label for="prospect-size">Planning for</label><select id="prospect-size"><option value="one or two">one or two people</option><option value="a small group">a small group</option><option value="a larger group">a larger group</option></select><label for="prospect-timing">Timing</label><select id="prospect-timing"><option value="soon">soon</option><option value="later">later</option></select><button type="submit">Preview next step</button></form><p class="prospect-note" data-confirm>Submitting this preview does not contact the restaurant or create a reservation.</p></div>`;
  document.body.append(button, dialog);
  const result = dialog.querySelector('.prospect-result');
  const messages = {food:'Start with the menu page, then use the contact page for current service details.',drinks:'Explore the drinks or experience page, then confirm what is current before you go.',group:'Use the groups, events, or contact page to review the restaurant’s current guidance.',easy:'Open the visit or contact page first for location and practical details.'};
  button.addEventListener('click', () => dialog.showModal());
  dialog.querySelector('.prospect-close').addEventListener('click', () => dialog.close());
  dialog.querySelectorAll('[data-p]').forEach((choice) => choice.addEventListener('click', () => { dialog.querySelectorAll('[data-p]').forEach((x) => x.setAttribute('aria-pressed','false')); choice.setAttribute('aria-pressed','true'); result.textContent = messages[choice.dataset.p]; }));
  dialog.querySelector('form').addEventListener('submit', (event) => { event.preventDefault(); const size=dialog.querySelector('#prospect-size').value, timing=dialog.querySelector('#prospect-timing').value; dialog.querySelector('[data-confirm]').textContent = `For ${size} visiting ${timing}: this is a demo-only planning preview. Use the restaurant’s official contact route to confirm current availability.`; });
})();
